apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_02c2f503ed33
          # env:
          #   - name: REACT_APP_API_BASE_URL
          #     value: http://localhost:8080/
          env:
            - name: REACT_APP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  #name: fe-env
                  #key: REACT_APP_API_BASE_URL
                  name: fe-deploy
                  key: REACT_APP_API_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
